---
title: System.IdentityModel.IdentityModelAsyncCallbackThrewException
ms.date: 03/30/2017
ms.assetid: e4fc924f-3b9e-44f5-97e4-b3a4bb855d89
ms.openlocfilehash: 16cf95c875b18ea89a0bde0a1c5f88f4a20bf544
ms.sourcegitcommit: 6b308cf6d627d78ee36dbbae8972a310ac7fd6c8
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 01/23/2019
ms.locfileid: "54505216"
---
# <a name="systemidentitymodelidentitymodelasynccallbackthrewexception"></a>System.IdentityModel.IdentityModelAsyncCallbackThrewException
System.IdentityModel.IdentityModelAsyncCallbackThrewException  
  
## <a name="description"></a>Descripción  
 Una devolución de llamada asincrónica produjo una excepción.  
  
## <a name="see-also"></a>Vea también
- [Traza](../../../../../docs/framework/wcf/diagnostics/tracing/index.md)
- [Uso del seguimiento para solucionar problemas de su aplicación](../../../../../docs/framework/wcf/diagnostics/tracing/using-tracing-to-troubleshoot-your-application.md)
- [Administración y diagnóstico](../../../../../docs/framework/wcf/diagnostics/index.md)
